const URL = {
  layout: '/layout',
  center: '/layout/center',
  flex: '/layout/flex',
  float: '/layout/float',
  grid: '/layout/grid',
  row: '/layout/row',
  spacing: '/layout/spacing',
  stack: '/layout/stack',
  components: '/components',
  badge: '/components/badge',
  button: '/components/button',
  input: '/components/input',
  checkbox: '/components/checkbox',
  popup: '/components/popup',
  progressBar: '/components/progress-bar',
  radio: '/components/radio',
  radioGroup: '/components/radio-group',
  spinner: '/components/spinner',
  switch: '/components/switch',
  tab: '/components/tab',
  dataTable: '/components/data-table',
  hooks: '/hooks',
  useTrie: '/hooks/use-trie',
};

export { URL };
