const URL = {
  root: '/',
  ui: '/ui',
  layout: '/ui/layout',
  center: '/ui/layout/center',
  flex: '/ui/layout/flex',
  float: '/ui/layout/float',
  grid: '/ui/layout/grid',
  row: '/ui/layout/row',
  spacing: '/ui/layout/spacing',
  stack: '/ui/layout/stack',
  uiComponents: '/ui/components',
  badge: '/ui/components/badge',
  button: '/ui/components/button',
  input: '/ui/components/input',
  checkbox: '/ui/components/checkbox',
  popup: '/ui/components/popup',
  progressBar: '/ui/components/progress-bar',
  radio: '/ui/components/radio',
  radioGroup: '/ui/components/radio-group',
  spinner: '/ui/components/spinner',
  switch: '/ui/components/switch',
  tab: '/ui/components/tab',
  dataTable: '/ui/components/data-table',
  textarea: '/ui/components/textarea',
  modules: '/modules',
  hooks: '/modules/hooks',
  useTrie: '/modules/hooks/use-trie',
  moduleComponents: '/modules/components',
  infiniteScroll: '/modules/components/infinite-scroll',
};

export { URL };
