const URL = {
  uiKit: '/ui-kit',
  layout: '/ui-kit/layout',
  center: '/ui-kit/layout/center',
  flex: '/ui-kit/layout/flex',
  float: '/ui-kit/layout/float',
  grid: '/ui-kit/layout/grid',
  row: '/ui-kit/layout/row',
  spacing: '/ui-kit/layout/spacing',
  stack: '/ui-kit/layout/stack',
  components: '/ui-kit/components',
  badge: '/ui-kit/components/badge',
  button: '/ui-kit/components/button',
  input: '/ui-kit/components/input',
  checkbox: '/ui-kit/components/checkbox',
  popup: '/ui-kit/components/popup',
  progressBar: '/ui-kit/components/progress-bar',
  radio: '/ui-kit/components/radio',
  radioGroup: '/ui-kit/components/radio-group',
  spinner: '/ui-kit/components/spinner',
  switch: '/ui-kit/components/switch',
  tab: '/ui-kit/components/tab',
  dataTable: '/ui-kit/components/data-table',
  modules: '/modules',
  hooks: '/modules/hooks',
  useTrie: '/modules/hooks/use-trie',
};

export { URL };
