import type { Documents } from '@src/store/pageContents/uiDocs/state';

import DataTableView from './DataTableView/DataTableView';
import Container from './Container/Container';
import Caption from './Caption/Caption';
import Thead from './Thead/Thead';
import Tbody from './Tbody/Tbody';
import Tfoot from './Tfoot/Tfoot';
import Pagination from './Pagination/Pagination';

const documents: Array<Documents> = [
  {
    title: 'DataTableContainer 컴포넌트',
    description: '테이블을 감싸는 컨테이너 입니다.',
    view: <Container />,
    componentString: [
      `<DataTableContainer>Data Table Container</DataTableContainer>`,
    ],
  },
  {
    title: 'DataTable Caption 컴포넌트',
    description: 'DataTable의 caption을 정의하는 컴포넌트 입니다.',
    view: <Caption />,
    componentString: [
      `<DataTableContainer>`,
      `    <DataTable>`,
      `        <DataTable.Caption>caption</DataTable.Caption>`,
      `    </DataTable>`,
      `</DataTableContainer>`,
    ],
  },
  {
    title: 'DataTable Thead 컴포넌트',
    description: 'DataTable의 Head를 보여주는 컴포넌트 입니다.',
    view: <Thead />,
    componentString: [
      `<DataTableContainer>`,
      `    <DataTable>`,
      `        <DataTable.Thead>`,
      `            <DataTable.Tr>`,
      `                <DataTable.Th>head1</DataTable.Th>`,
      `                <DataTable.Th>head2</DataTable.Th>`,
      `                <DataTable.Th>head3</DataTable.Th>`,
      `            </DataTable.Tr>`,
      `        </DataTable.Thead>`,
      `    </DataTable>`,
      `</DataTableContainer>`,
    ],
  },
  {
    title: 'DataTable Tbody 컴포넌트',
    description: 'DataTable의 Body를 보여주는 컴포넌트 입니다.',
    view: <Tbody />,
    componentString: [
      `<DataTableContainer>`,
      `    <DataTable>`,
      `        <DataTable.Tbody>`,
      `            <DataTable.Tr>`,
      `                <DataTable.Td>data1</DataTable.Td>`,
      `                <DataTable.Td>data2</DataTable.Td>`,
      `                <DataTable.Td>data3</DataTable.Td>`,
      `            </DataTable.Tr>`,
      `            <DataTable.Tr>`,
      `                <DataTable.Td>data1</DataTable.Td>`,
      `                <DataTable.Td>data2</DataTable.Td>`,
      `                <DataTable.Td>data3</DataTable.Td>`,
      `            </DataTable.Tr>`,
      `            <DataTable.Tr disabled>`,
      `                <DataTable.Td>data1</DataTable.Td>`,
      `                <DataTable.Td>data2</DataTable.Td>`,
      `                <DataTable.Td>data3</DataTable.Td>`,
      `            </DataTable.Tr>`,
      `            <DataTable.Tr>`,
      `                <DataTable.Td>data1</DataTable.Td>`,
      `                <DataTable.Td>data2</DataTable.Td>`,
      `                <DataTable.Td>data3</DataTable.Td>`,
      `            </DataTable.Tr>`,
      `        </DataTable.Tbody>`,
      `    </DataTable>`,
      `</DataTableContainer>`,
    ],
  },
  {
    title: 'DataTable Tfoot 컴포넌트',
    description: 'DataTable의 Body를 보여주는 컴포넌트 입니다.',
    view: <Tfoot />,
    componentString: [
      `<DataTableContainer>`,
      `    <DataTable>`,
      `        <DataTable.Tfoot>`,
      `            <DataTable.Tr>`,
      `                <DataTable.Th>foot1</DataTable.Th>`,
      `                <DataTable.Th>foot2</DataTable.Th>`,
      `                <DataTable.Th>foot3</DataTable.Th>`,
      `            </DataTable.Tr>`,
      `        </DataTable.Tfoot>`,
      `    </DataTable>`,
      `</DataTableContainer>`,
    ],
  },
  {
    title: 'DataTable Pagination 컴포넌트',
    description: 'DataTable의 페이지네이션 UI 입니다.',
    view: <Pagination />,
    componentString: [
      `<DataTableContainer>`,
      `    <DataTable.Pagination lastPageIndex={55} />`,
      `</DataTableContainer>`,
    ],
  },
  {
    title: 'DataTable 컴포넌트',
    description: 'DataTable 컴포넌트 입니다.',
    view: <DataTableView />,
    componentString: [
      `<DataTableContainer>`,
      `    <DataTable>`,
      `        <DataTable.Caption>caption</DataTable.Caption>`,
      `        <DataTable.Thead>`,
      `            <DataTable.Tr>`,
      `                <DataTable.Th>head1</DataTable.Th>`,
      `                <DataTable.Th>head2</DataTable.Th>`,
      `                <DataTable.Th>head3</DataTable.Th>`,
      `            </DataTable.Tr>`,
      `        </DataTable.Thead>`,
      `        <DataTable.Tbody>`,
      `            <DataTable.Tr>`,
      `                <DataTable.Td>data1</DataTable.Td>`,
      `                <DataTable.Td>data2</DataTable.Td>`,
      `                <DataTable.Td>data3</DataTable.Td>`,
      `            </DataTable.Tr>`,
      `            <DataTable.Tr>`,
      `                <DataTable.Td>data1</DataTable.Td>`,
      `                <DataTable.Td>data2</DataTable.Td>`,
      `                <DataTable.Td>data3</DataTable.Td>`,
      `            </DataTable.Tr>`,
      `            <DataTable.Tr disabled>`,
      `                <DataTable.Td>data1</DataTable.Td>`,
      `                <DataTable.Td>data2</DataTable.Td>`,
      `                <DataTable.Td>data3</DataTable.Td>`,
      `            </DataTable.Tr>`,
      `            <DataTable.Tr>`,
      `                <DataTable.Td>data1</DataTable.Td>`,
      `                <DataTable.Td>data2</DataTable.Td>`,
      `                <DataTable.Td>data3</DataTable.Td>`,
      `            </DataTable.Tr>`,
      `        </DataTable.Tbody>`,
      `        <DataTable.Tfoot>`,
      `            <DataTable.Tr>`,
      `                <DataTable.Th>foot1</DataTable.Th>`,
      `                <DataTable.Th>foot2</DataTable.Th>`,
      `                <DataTable.Th>foot3</DataTable.Th>`,
      `            </DataTable.Tr>`,
      `        </DataTable.Tfoot>`,
      `        <DataTable.Pagination lastPage={55} />`,
      `    </DataTable>`,
      `</DataTableContainer>`,
    ],
  },
];

export { documents };
