#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_msg_file=".git/COMMIT_EDITMSG"

commit_msg=$(cat "$commit_msg_file")

workspace="workspace"
react_ui="react-ui"
react_modules="react-modules"
documents="docs"

echo "Last commit [$commit_msg]."
if [[ $commit_msg == *"$workspace"* ]]; then
  yarn wk:rmo tsc && yarn wk:rui tsc && yarn wk:docs tsc
elif [[ $commit_msg == *"$react_ui"* ]]; then
  yarn wk:rui tsc && yarn wk:rui build
elif [[ $commit_msg == *"$react_modules"* ]]; then
  yarn wk:rmo tsc && yarn wk:rmo build
elif [[ $commit_msg == *"$documents"* ]]; then
  yarn wk:docs tsc && yarn wk:docs build
else 
  echo "커밋 메시지를 다시 확인하세요."
  exit 1
fi

